## Refs: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
##
## Default values for kube-prometheus-stack.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
##

%{~ if trimspace(regcred) != "" }
global:
  imagePullSecrets:
    - name: ${regcred}
%{~ endif }

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  %{~ if trimspace(grafana_ingress_host) != "" ~}
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true
    %{~ if trimspace(grafana_ingress_class) != "" ~}
    ingressClassName: ${grafana_ingress_class}
    %{~ endif ~}
    %{~ if (trimspace(grafana_cluster_issuer_name) != "" || trimspace(grafana_ingress_basic_auth_username) != "") ~}
    annotations:
      %{~ if trimspace(grafana_cluster_issuer_name) != "" ~}
      cert-manager.io/cluster-issuer: "${grafana_cluster_issuer_name}"
      acme.cert-manager.io/http01-edit-in-place: "true"
      %{~ endif ~}
      %{~ if trimspace(grafana_ingress_basic_auth_username) != "" ~}
      nginx.ingress.kubernetes.io/auth-type: "basic"
      nginx.ingress.kubernetes.io/auth-realm: "${grafana_ingress_basic_auth_message}"
      nginx.ingress.kubernetes.io/auth-secret: "${grafana_ingress_basic_auth_secret}"
      %{~ endif ~}
    %{~ endif ~}
    hosts:
      - ${grafana_ingress_host}
    %{~ if trimspace(grafana_cluster_issuer_name) != "" ~}
    tls:
      - secretName: ${cert_manager_secret_name}
        hosts:
          - ${grafana_ingress_host}
    %{~ endif ~}
  %{~ endif ~}
  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 100Gi

# Disable Etcd metrics
kubeEtcd:
  enabled: false

# Disable Controller metrics
kubeControllerManager:
  enabled: false

# Disable Scheduler metrics
kubeScheduler:
  enabled: false

# Disable alertmanager
alertmanager:
  enabled: false
